import { Property } from './types';

export const initialProperties: Property[] = [
  {
    id: 'prop-1',
    title: 'Luxury 4 Bedroom Fully Detached Duplex',
    description: 'A masterpiece of architectural design located in the prestigious Lekki Phase 1. This luxury duplex features massive bedrooms, a fully fitted automated kitchen, high ceiling living area, swimming pool, and an in-built sound system. Situated in a clean, flood-free gated estate with 24/7 security and estate power.',
    price: 15000000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'duplex',
    state: 'Lagos',
    city: 'Lekki',
    area: 'Phase 1',
    bedrooms: 4,
    bathrooms: 5,
    squareMeters: 450,
    furnished: true,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['24/7 Power Supply', 'Swimming Pool', 'Armed Security', 'Fully Fitted Kitchen', 'Smart Home System', 'Boys Quarters', 'Water Treatment', 'Prepaid Meter'],
    nearbySchools: ['Lekki British International School', 'Meadow Hall School'],
    nearbyHospitals: ['Evercare Hospital Lekki', 'Reddington Hospital'],
    nearbySupermarkets: ['Ebenezer Supermarket', 'Prince Ebeano Supermarket'],
    agent: {
      id: 'agent-1',
      name: 'Chinedu Okafor',
      phone: '+234 812 345 6789',
      whatsapp: '2348123456789',
      email: 'chinedu.okafor@rentnaija.com',
      verified: true,
      badge: 'premium',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 6.4311, lng: 3.4839 },
    views: 1240,
    leads: 85,
    createdAt: '2026-07-10T12:00:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-2',
    title: 'Modern 2 Bedroom Serviced Apartment',
    description: 'Exquisitely finished 2 bedroom apartment located inside a very serene block of apartments in Maitama, Abuja. Features clean water, constant power, air conditioners fully installed, elevator access, and dedicated car park. Extremely popular with young professionals.',
    price: 8000000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'apartment',
    state: 'Abuja',
    city: 'Maitama',
    area: 'Maitama Extension',
    bedrooms: 2,
    bathrooms: 2,
    squareMeters: 180,
    furnished: false,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Standby Generator', 'Uniformed Security', 'AC Installed', 'Water Heater', 'Elevator', 'Gym', 'Prepaid Meter'],
    nearbySchools: ['British Nigerian Academy', 'Funtaj International School'],
    nearbyHospitals: ['Maitama District Hospital', 'National Hospital Abuja'],
    nearbySupermarkets: ['Exclusive Supermarket', 'Next Cash and Carry'],
    agent: {
      id: 'agent-2',
      name: 'Amina Yusuf',
      phone: '+234 905 111 2222',
      whatsapp: '2349051112222',
      email: 'amina.yusuf@rentnaija.com',
      verified: true,
      badge: 'verified',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 9.0765, lng: 7.4984 },
    views: 890,
    leads: 42,
    createdAt: '2026-07-12T10:30:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-3',
    title: 'Premium Block of 500 SQM Commercial Office Space',
    description: 'A-grade commercial office space located on the high street of Victoria Island, Lagos. This corporate hub offers massive open floor plan, central air conditioning, fire alarm system, high-speed elevator, and basement parking for up to 20 cars. Includes 24/7 security patrols.',
    price: 45000000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'office',
    state: 'Lagos',
    city: 'Victoria Island',
    area: 'Adeola Odeku',
    bedrooms: 0,
    bathrooms: 6,
    squareMeters: 500,
    furnished: false,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Central Air-Conditioning', 'Basement Parking', 'Corporate Security', 'CCTV System', 'Fitted Elevators', 'Fibre Internet Ready'],
    nearbySchools: ['Corona Primary School', 'Adrao International School'],
    nearbyHospitals: ['St. Nicholas Hospital', 'Reddington Hospital VI'],
    nearbySupermarkets: ['Hubmart Supermarket', 'Mega Plaza'],
    agent: {
      id: 'agent-1',
      name: 'Chinedu Okafor',
      phone: '+234 812 345 6789',
      whatsapp: '2348123456789',
      email: 'chinedu.okafor@rentnaija.com',
      verified: true,
      badge: 'premium',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 6.4281, lng: 3.4219 },
    views: 450,
    leads: 18,
    createdAt: '2026-07-14T08:15:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-4',
    title: 'Executive 3 Bedroom Bungalow with Boys Quarters',
    description: 'A beautifully built executive 3-bedroom bungalow located in a secure and gated community in Bodija, Ibadan. Features spacious living and dining area, modern POP ceilings, high quality marble floors, and a spacious compound that can pack 4 cars. Perfect for families looking for peaceful living.',
    price: 32000000,
    period: 'total',
    type: 'sale',
    propertyType: 'bungalow',
    state: 'Oyo',
    city: 'Ibadan',
    area: 'Bodija',
    bedrooms: 3,
    bathrooms: 4,
    squareMeters: 380,
    furnished: false,
    verified: false,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['POP Ceilings', 'Car Park', 'Spacious Compound', 'Fenced and Gated', 'Water Heater', 'Prepaid Meter'],
    nearbySchools: ['University of Ibadan Staff School', 'International School Ibadan'],
    nearbyHospitals: ['University College Hospital (UCH)', 'J-Rapha Hospital'],
    nearbySupermarkets: ['FoodCo Bodija', 'Ace Supermarket'],
    agent: {
      id: 'agent-3',
      name: 'Kunle Adeleke',
      phone: '+234 803 777 8888',
      whatsapp: '2348037778888',
      email: 'kunle.adeleke@rentnaija.com',
      verified: false,
      badge: 'standard',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 7.4162, lng: 3.9168 },
    views: 620,
    leads: 29,
    createdAt: '2026-07-15T15:45:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-5',
    title: 'Affordable Serviced Self-Contain Room',
    description: 'Neat and cozy self-contain (studio apartment) located in Akoka, Yaba, just 5 minutes walk from the University of Lagos (UNILAG). This property is perfect for students or young working class professionals starting out in Lagos. Includes water supply and central generator support.',
    price: 650000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'self-contain',
    state: 'Lagos',
    city: 'Yaba',
    area: 'Akoka',
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 45,
    furnished: false,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Gated Compound', 'Borehole Water', 'Tiled Floor', 'Wardrobe', 'Prepaid Meter'],
    nearbySchools: ['University of Lagos', 'Federal College of Education'],
    nearbyHospitals: ['Military Hospital Yaba', 'Federal Neuro-Psychiatric Hospital'],
    nearbySupermarkets: ['Sujay Supermarket', 'Tantalizers Mall'],
    agent: {
      id: 'agent-3',
      name: 'Kunle Adeleke',
      phone: '+234 803 777 8888',
      whatsapp: '2348037778888',
      email: 'kunle.adeleke@rentnaija.com',
      verified: true,
      badge: 'standard',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 6.5181, lng: 3.3892 },
    views: 2450,
    leads: 184,
    createdAt: '2026-07-17T11:00:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-6',
    title: '6 plots of prime dry land in Ibeju Lekki',
    description: 'An excellent investment opportunity: 6 plots of 100% dry and flat land located at Ibeju-Lekki, close to the Dangote Refinery and Lekki Free Trade Zone. Fully fenced and gated with a clean Certificate of Ownership (C of O) ready for immediate development.',
    price: 90000000,
    period: 'total',
    type: 'sale',
    propertyType: 'land',
    state: 'Lagos',
    city: 'Ibeju Lekki',
    area: 'Eleko',
    bedrooms: 0,
    bathrooms: 0,
    squareMeters: 3600,
    furnished: false,
    verified: true,
    featured: true,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Fenced Compound', 'Gated Access', 'Clean Deed', 'Dry Land', 'Electricity Closeby'],
    nearbySchools: ['Pan-Atlantic University', 'Greenwood House School'],
    nearbyHospitals: ['General Hospital Ibeju-Lekki', 'St. Edward Clinic'],
    nearbySupermarkets: ['Refinery Workers Supermarket', 'Pinnacle Mall'],
    agent: {
      id: 'agent-1',
      name: 'Chinedu Okafor',
      phone: '+234 812 345 6789',
      whatsapp: '2348123456789',
      email: 'chinedu.okafor@rentnaija.com',
      verified: true,
      badge: 'premium',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 6.4673, lng: 3.8219 },
    views: 520,
    leads: 31,
    createdAt: '2026-07-18T14:20:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-7',
    title: 'Modern Mini Flat (1 Bedroom Apartment)',
    description: 'A spacious and newly built mini-flat in Surulere, Lagos. It features a large living room, guest toilet, a clean ensuite bedroom, kitchen cabinets, and separate electricity prepayment meter. Safe environment with uniform street security.',
    price: 1200000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'mini-flat',
    state: 'Lagos',
    city: 'Surulere',
    area: 'Adeniran Ogunsanya',
    bedrooms: 1,
    bathrooms: 2,
    squareMeters: 85,
    furnished: false,
    verified: true,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Ensuite Bedroom', 'Guest Toilet', 'Kitchen Cabinets', 'Prepaid Meter', 'Street Security', 'Water Treatment'],
    nearbySchools: ['Surulere Baptist High School', 'Queen\'s College'],
    nearbyHospitals: ['Randle General Hospital', 'LUTH (Lagos University Teaching Hospital)'],
    nearbySupermarkets: ['Shoprite Surulere', 'Spar Lekki'],
    agent: {
      id: 'agent-2',
      name: 'Amina Yusuf',
      phone: '+234 905 111 2222',
      whatsapp: '2349051112222',
      email: 'amina.yusuf@rentnaija.com',
      verified: true,
      badge: 'verified',
      image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 6.5012, lng: 3.3582 },
    views: 1820,
    leads: 110,
    createdAt: '2026-07-19T09:00:00Z',
    approved: true,
    reported: false
  },
  {
    id: 'prop-8',
    title: 'Student Housing Shared Apartment near UNIPORT',
    description: 'Shared student apartment located in Aluu, close to the University of Port Harcourt (UNIPORT), Rivers State. Single bedroom inside a massive 3-bedroom flat. Kitchen and living area are shared. Constant security patrol, high speed Wi-Fi, and stable water.',
    price: 350000,
    period: 'yearly',
    type: 'rent',
    propertyType: 'student',
    state: 'Rivers',
    city: 'Port Harcourt',
    area: 'Aluu',
    bedrooms: 1,
    bathrooms: 1,
    squareMeters: 30,
    furnished: true,
    verified: false,
    featured: false,
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'
    ],
    amenities: ['Furnished Room', 'Shared Kitchen', 'Shared Living Room', 'Student Security', 'Borehole Water', 'Unlimited Wi-Fi'],
    nearbySchools: ['University of Port Harcourt', 'Ignatius Ajuru University'],
    nearbyHospitals: ['UPTH (University of Port Harcourt Teaching Hospital)', 'Aluu Health Centre'],
    nearbySupermarkets: ['Port Harcourt Mall', 'Everyday Supermarket Aluu'],
    agent: {
      id: 'agent-4',
      name: 'Tamuno Briggs',
      phone: '+234 802 999 0000',
      whatsapp: '2348029990000',
      email: 'tamuno.briggs@rentnaija.com',
      verified: true,
      badge: 'verified',
      image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&h=400&q=80'
    },
    gps: { lat: 4.8994, lng: 6.9181 },
    views: 1540,
    leads: 95,
    createdAt: '2026-07-20T10:00:00Z',
    approved: true,
    reported: false
  }
];

export const statesAndCities: Record<string, string[]> = {
  'Lagos': ['Lekki', 'Victoria Island', 'Ikoyi', 'Ikeja', 'Surulere', 'Yaba', 'Ibeju Lekki', 'Gbagada'],
  'Abuja': ['Maitama', 'Asokoro', 'Wuse II', 'Gwarinpa', 'Garki', 'Apo', 'Jabi'],
  'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Aluu'],
  'Oyo': ['Ibadan', 'Ogbomosho'],
  'Enugu': ['Enugu', 'Nsukka'],
  'Kano': ['Kano', 'Gwale']
};

export const categories = [
  { id: 'apartment', name: 'Apartments', count: 124, icon: 'Home' },
  { id: 'duplex', name: 'Duplexes', count: 85, icon: 'Building' },
  { id: 'bungalow', name: 'Bungalows', count: 42, icon: 'Home' },
  { id: 'self-contain', name: 'Self-Contain', count: 98, icon: 'Inbox' },
  { id: 'mini-flat', name: 'Mini Flats', count: 110, icon: 'Building2' },
  { id: 'shared', name: 'Shared Apartments', count: 35, icon: 'Users' },
  { id: 'student', name: 'Student Housing', count: 64, icon: 'GraduationCap' },
  { id: 'office', name: 'Offices', count: 28, icon: 'Briefcase' },
  { id: 'shop', name: 'Shops', count: 57, icon: 'ShoppingBag' },
  { id: 'warehouse', name: 'Warehouses', count: 12, icon: 'Warehouse' },
  { id: 'land', name: 'Lands', count: 145, icon: 'Map' }
];
